<p style="text-align:center">
    <a href="https://skills.network" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo">
    </a>
</p>

<h1 align=center><font size = 5>Assignment: SQL Notebook for Peer Assignment</font></h1>

Estimated time needed: **60** minutes.

## Introduction
Using this Python notebook you will:

1.  Understand the Spacex DataSet
2.  Load the dataset  into the corresponding table in a Db2 database
3.  Execute SQL queries to answer assignment questions

## Overview of the DataSet

SpaceX has gained worldwide attention for a series of historic milestones. 

It is the only private company ever to return a spacecraft from low-earth orbit, which it first accomplished in December 2010.
SpaceX advertises Falcon 9 rocket launches on its website with a cost of 62 million dollars wheras other providers cost upward of 165 million dollars each, much of the savings is because Space X can reuse the first stage. 


Therefore if we can determine if the first stage will land, we can determine the cost of a launch. 

This information can be used if an alternate company wants to bid against SpaceX for a rocket launch.

This dataset includes a record for each payload carried during a SpaceX mission into outer space.

### Download the datasets

This assignment requires you to load the spacex dataset.

In many cases the dataset to be analyzed is available as a .CSV (comma separated values) file, perhaps on the internet. Click on the link below to download and save the dataset (.CSV file):

 <a href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_2/data/Spacex.csv" target="_blank">Spacex DataSet</a>

In [1]:
!pip install sqlalchemy==1.3.9

Collecting sqlalchemy==1.3.9
  Downloading SQLAlchemy-1.3.9.tar.gz (6.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.0/6.0 MB 13.0 MB/s eta 0:00:0000:0100:01
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: sqlalchemy
  Building wheel for sqlalchemy (setup.py) ... done
  Created wheel for sqlalchemy: filename=SQLAlchemy-1.3.9-cp311-cp311-macosx_10_9_x86_64.whl size=1153814 sha256=92dd967afaac9c7ed107a3bf338279e9f1612c4708a2c66f43ce25801fa5e6c6
  Stored in directory: /Users/benmatthew/Library/Caches/pip/wheels/3a/7c/1e/12404784a68083eb969f877a1808a1847bab897684b56ddc55
Successfully built sqlalchemy
Installing collected packages: sqlalchemy
  Attempting uninstall: sqlalchemy
    Found existing installation: SQLAlchemy 1.4.39
    Uninstalling SQLAlchemy-1.4.39:
      Successfully uninstalled SQLAlchemy-1.4.39
Successfully installed sqlalchemy-1.3.9

In [3]:
!pip install sql

Collecting sql
  Downloading sql-2022.4.0.tar.gz (4.2 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: sql
  Building wheel for sql (setup.py) ... done
  Created wheel for sql: filename=sql-2022.4.0-py3-none-any.whl size=4307 sha256=9e9efa682dc9e774cd9f61dddabc621549f52e5fd924ee485f928ec67e2fc60a
  Stored in directory: /Users/benmatthew/Library/Caches/pip/wheels/a6/f1/62/be6faba20c8384c5766c0332c93841b610ab2602d6ae312bbf
Successfully built sql
Installing collected packages: sql
Successfully installed sql-2022.4.0

### Connect to the database

Let us first load the SQL extension and establish a connection with the database

In [4]:
%load_ext sql

The sql module is not an IPython extension.

In [5]:
import csv, sqlite3

con = sqlite3.connect("my_data1.db")
cur = con.cursor()

In [6]:
!pip install -q pandas==1.1.5

^C
ERROR: Operation cancelled by user

In [7]:
%sql sqlite:///my_data1.db

UsageError: Line magic function `%sql` not found.

In [8]:
import pandas as pd
df = pd.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_2/data/Spacex.csv")
df.to_sql("SPACEXTBL", con, if_exists='replace', index=False,method="multi")

101

In [12]:
df = pd.read_csv('Spacex.csv')

,Date,Time (UTC),Booster_Version,Launch_Site,Payload,PAYLOAD_MASS__KG_,Orbit,Customer,Mission_Outcome,Landing_Outcome
0,2010-06-04,18:45:00,F9 v1.0 B0003,CCAFS LC-40,Dragon Spacecraft Qualification Unit,0,LEO,SpaceX,Success,Failure (parachute)
1,2010-12-08,15:43:00,F9 v1.0 B0004,CCAFS LC-40,"Dragon demo flight C1, two CubeSats, barrel of...",0,LEO (ISS),NASA (COTS) NRO,Success,Failure (parachute)
2,2012-05-22,7:44:00,F9 v1.0 B0005,CCAFS LC-40,Dragon demo flight C2,525,LEO (ISS),NASA (COTS),Success,No attempt
3,2012-10-08,0:35:00,F9 v1.0 B0006,CCAFS LC-40,SpaceX CRS-1,500,LEO (ISS),NASA (CRS),Success,No attempt
4,2013-03-01,15:10:00,F9 v1.0 B0007,CCAFS LC-40,SpaceX CRS-2,677,LEO (ISS),NASA (CRS),Success,No attempt
...,...,...,...,...,...,...,...,...,...,...
96,2020-11-05,23:24:23,F9 B5B1062.1,CCAFS SLC-40,"GPS III-04 , Crew-1",4311,MEO,USSF,Success,Success
97,2020-11-16,0:27:00,F9 B5B1061.1,KSC LC-39A,"Crew-1, Sentinel-6 Michael Freilich",12500,LEO (ISS),NASA (CCP),Success,Success
98,2020-11-21,17:17:08,F9 B5B1063.1,VAFB SLC-4E,"Sentinel-6 Michael Freilich, Starlink 15 v1.0",1192,LEO,NASA / NOAA / ESA / EUMETSAT,Success,Success
99,2020-11-25,2:13:00,F9 B5 B1049.7,CCAFS SLC-40,"Starlink 15 v1.0, SpaceX CRS-21",15600,LEO,SpaceX,Success,Success
100,2020-12-06,16:17:08,F9 B5 B1058.4,KSC LC-39A,SpaceX CRS-21,2972,LEO (ISS),NASA (CRS),Success,Success

**Note:This below code is added to remove blank rows from table**

In [9]:
%sql create table SPACEXTABLE as select * from SPACEXTBL where Date is not null

UsageError: Line magic function `%sql` not found.

## Tasks

Now write and execute SQL queries to solve the assignment tasks.

**Note: If the column names are in mixed case enclose it in double quotes
   For Example "Landing_Outcome"**

### Task 1




##### Display the names of the unique launch sites  in the space mission

In [14]:
df['Launch_Site'].value_counts()

Launch_Site
CCAFS SLC-40    34
CCAFS LC-40     26
KSC LC-39A      25
VAFB SLC-4E     16
Name: count, dtype: int64


### Task 2


#####  Display 5 records where launch sites begin with the string 'CCA'

In [15]:
df[df['Launch_Site'] == 'CCAFS SLC-40']

,Date,Time (UTC),Booster_Version,Launch_Site,Payload,PAYLOAD_MASS__KG_,Orbit,Customer,Mission_Outcome,Landing_Outcome
44,2017-12-15,15:36:00,F9 FT B1035.2,CCAFS SLC-40,SpaceX CRS-13,2205,LEO (ISS),NASA (CRS),Success,Success (ground pad)
46,2018-01-08,1:00:00,F9 B4 B1043.1,CCAFS SLC-40,Zuma,5000,LEO,Northrop Grumman,Success (payload status unclear),Success (ground pad)
47,2018-01-31,21:25:00,F9 FT B1032.2,CCAFS SLC-40,GovSat-1 / SES-16,4230,GTO,SES,Success,Controlled (ocean)
49,2018-03-06,5:33:00,F9 B4 B1044,CCAFS SLC-40,Hispasat 30W-6 PODSat,6092,GTO,Hispasat NovaWurks,Success,No attempt
51,2018-04-02,20:30:00,F9 B4 B1039.2,CCAFS SLC-40,SpaceX CRS-14,2647,LEO (ISS),NASA (CRS),Success,No attempt
52,2018-04-18,22:51:00,F9 B4 B1045.1,CCAFS SLC-40,Transiting Exoplanet Survey Satellite (TESS),362,HEO,NASA (LSP),Success,Success (drone ship)
55,2018-06-04,4:45:00,F9 B4 B1040.2,CCAFS SLC-40,SES-12,5384,GTO,SES,Success,No attempt
56,2018-06-29,9:42:00,F9 B4 B1045.2,CCAFS SLC-40,SpaceX CRS-15,2697,LEO (ISS),NASA (CRS),Success,No attempt
57,2018-07-22,5:50:00,F9 B5B1047.1,CCAFS SLC-40,Telstar 19V,7075,GTO,Telesat,Success,Success
59,2018-08-07,5:18:00,F9 B5 B1046.2,CCAFS SLC-40,Merah Putih,5800,GTO,Telkom Indonesia,Success,Success
60,2018-09-10,4:45:00,F9 B5B1049.1,CCAFS SLC-40,Telstar 18V / Apstar-5C,7060,GTO,Telesat,Success,Success
64,2018-12-05,18:16:00,F9 B5B1050,CCAFS SLC-40,SpaceX CRS-16,2500,LEO (ISS),NASA (CRS),Success,Failure
65,2018-12-23,13:51:00,F9 B5B1054,CCAFS SLC-40,GPS III-01,4400,MEO,USAF,Success,No attempt
67,2019-02-22,1:45:00,F9 B5 B1048.3,CCAFS SLC-40,"Nusantara Satu, Beresheet Moon lander, S5",4850,GTO,"PSN, SpaceIL / IAI",Success,Success
69,2019-05-04,6:48:00,F9 B5B1056.1,CCAFS SLC-40,"SpaceX CRS-17, Starlink v0.9",2495,LEO (ISS),NASA (CRS),Success,Success
70,2019-05-24,2:30:00,F9 B5 B1049.3,CCAFS SLC-40,"Starlink v0.9, RADARSAT Constellation",13620,LEO,SpaceX,Success,Success
72,2019-07-25,22:01:00,F9 B5 B1056.2,CCAFS SLC-40,"SpaceX CRS-18, AMOS-17",2268,LEO (ISS),NASA (CRS),Success,Success
73,2019-08-06,23:23:00,F9 B5 B1047.3,CCAFS SLC-40,"AMOS-17, Starlink 1 v1.0",6500,GTO,Spacecom,Success,No attempt
74,2019-11-11,14:56:00,F9 B5 B1048.4,CCAFS SLC-40,"Starlink 1 v1.0, SpaceX CRS-19",15600,LEO,SpaceX,Success,Success
75,2019-12-05,17:29:00,F9 B5B1059.1,CCAFS SLC-40,"SpaceX CRS-19, JCSat-18 / Kacific 1",2617,LEO (ISS),"NASA (CRS), Kacific 1",Success,Success
76,2019-12-17,0:10:00,F9 B5 B1056.3,CCAFS SLC-40,"JCSat-18 / Kacific 1, Starlink 2 v1.0",6956,GTO,"Sky Perfect JSAT, Kacific 1",Success,Success
77,2020-01-07,2:33:00,F9 B5 B1049.4,CCAFS SLC-40,"Starlink 2 v1.0, Crew Dragon in-flight abort t...",15600,LEO,SpaceX,Success,Success
79,2020-01-29,14:07:00,F9 B5 B1051.3,CCAFS SLC-40,"Starlink 3 v1.0, Starlink 4 v1.0",15600,LEO,SpaceX,Success,Success
80,2020-02-17,15:05:00,F9 B5 B1056.4,CCAFS SLC-40,"Starlink 4 v1.0, SpaceX CRS-20",15600,LEO,SpaceX,Success,Failure
81,2020-03-07,4:50:00,F9 B5 B1059.2,CCAFS SLC-40,"SpaceX CRS-20, Starlink 5 v1.0",1977,LEO (ISS),NASA (CRS),Success,Success
85,2020-06-04,1:25:00,F9 B5 B1049.5,CCAFS SLC-40,"Starlink 7 v1.0, Starlink 8 v1.0",15600,LEO,"SpaceX, Planet Labs",Success,Success
86,2020-06-13,9:21:00,F9 B5 B1059.3,CCAFS SLC-40,"Starlink 8 v1.0, SkySats-16, -17, -18, GPS III...",15410,LEO,"SpaceX, Planet Labs",Success,Success
87,2020-06-30,20:10:46,F9 B5B1060.1,CCAFS SLC-40,"GPS III-03, ANASIS-II",4311,MEO,U.S. Space Force,Success,Success
88,2020-07-20,21:30:00,F9 B5 B1058.2,CCAFS SLC-40,"ANASIS-II, Starlink 9 v1.0",5500,GTO,"Republic of Korea Army, Spaceflight Industries...",Success,Success
90,2020-08-18,14:31:00,F9 B5 B1049.6,CCAFS SLC-40,"Starlink 10 v1.0, SkySat-19, -20, -21, SAOCOM 1B",15440,LEO,"SpaceX, Planet Labs, PlanetIQ",Success,Success
91,2020-08-30,23:18:00,F9 B5 B1059.4,CCAFS SLC-40,"SAOCOM 1B, GNOMES 1, Tyvak-0172",3130,SSO,"CONAE, PlanetIQ, SpaceX",Success,Success
95,2020-10-24,15:31:34,F9 B5 B1060.3,CCAFS SLC-40,"Starlink 14 v1.0, GPS III-04",15600,LEO,SpaceX,Success,Success
96,2020-11-05,23:24:23,F9 B5B1062.1,CCAFS SLC-40,"GPS III-04 , Crew-1",4311,MEO,USSF,Success,Success
99,2020-11-25,2:13:00,F9 B5 B1049.7,CCAFS SLC-40,"Starlink 15 v1.0, SpaceX CRS-21",15600,LEO,SpaceX,Success,Success

### Task 3




##### Display the total payload mass carried by boosters launched by NASA (CRS)

In [22]:
df[df['Customer'] == 'NASA (CRS)']['PAYLOAD_MASS__KG_'].sum()

45596

### Task 4




##### Display average payload mass carried by booster version F9 v1.1

In [24]:
df.head()

df[df['Booster_Version'] == 'F9 v1.1']['PAYLOAD_MASS__KG_'].mean()

2928.4

### Task 5

##### List the date when the first succesful landing outcome in ground pad was acheived.


_Hint:Use min function_

In [27]:
df[df['Landing_Outcome'] == 'Success (ground pad)']

,Date,Time (UTC),Booster_Version,Launch_Site,Payload,PAYLOAD_MASS__KG_,Orbit,Customer,Mission_Outcome,Landing_Outcome
19,2015-12-22,1:29:00,F9 FT B1019,CCAFS LC-40,OG2 Mission 2 11 Orbcomm-OG2 satellites,2034,LEO,Orbcomm,Success,Success (ground pad)
26,2016-07-18,4:45:00,F9 FT B1025.1,CCAFS LC-40,SpaceX CRS-9,2257,LEO (ISS),NASA (CRS),Success,Success (ground pad)
29,2017-02-19,14:39:00,F9 FT B1031.1,KSC LC-39A,SpaceX CRS-10,2490,LEO (ISS),NASA (CRS),Success,Success (ground pad)
32,2017-05-01,11:15:00,F9 FT B1032.1,KSC LC-39A,NROL-76,5300,LEO,NRO,Success,Success (ground pad)
34,2017-06-03,21:07:00,F9 FT B1035.1,KSC LC-39A,SpaceX CRS-11,2708,LEO (ISS),NASA (CRS),Success,Success (ground pad)
38,2017-08-14,16:31:00,F9 B4 B1039.1,KSC LC-39A,SpaceX CRS-12,3310,LEO (ISS),NASA (CRS),Success,Success (ground pad)
40,2017-09-07,14:00:00,F9 B4 B1040.1,KSC LC-39A,Boeing X-37B OTV-5,4990,LEO,U.S. Air Force,Success,Success (ground pad)
44,2017-12-15,15:36:00,F9 FT B1035.2,CCAFS SLC-40,SpaceX CRS-13,2205,LEO (ISS),NASA (CRS),Success,Success (ground pad)
46,2018-01-08,1:00:00,F9 B4 B1043.1,CCAFS SLC-40,Zuma,5000,LEO,Northrop Grumman,Success (payload status unclear),Success (ground pad)

### Task 6

##### List the names of the boosters which have success in drone ship and have payload mass greater than 4000 but less than 6000

In [31]:
df[df['Landing_Outcome'] == 'Success (drone ship)']

,Date,Time (UTC),Booster_Version,Launch_Site,Payload,PAYLOAD_MASS__KG_,Orbit,Customer,Mission_Outcome,Landing_Outcome
22,2016-04-08,20:43:00,F9 FT B1021.1,CCAFS LC-40,SpaceX CRS-8,3136,LEO (ISS),NASA (CRS),Success,Success (drone ship)
23,2016-05-06,5:21:00,F9 FT B1022,CCAFS LC-40,JCSAT-14,4696,GTO,SKY Perfect JSAT Group,Success,Success (drone ship)
24,2016-05-27,21:39:00,F9 FT B1023.1,CCAFS LC-40,Thaicom 8,3100,GTO,Thaicom,Success,Success (drone ship)
27,2016-08-14,5:26:00,F9 FT B1026,CCAFS LC-40,JCSAT-16,4600,GTO,SKY Perfect JSAT Group,Success,Success (drone ship)
28,2017-01-14,17:54:00,F9 FT B1029.1,VAFB SLC-4E,Iridium NEXT 1,9600,Polar LEO,Iridium Communications,Success,Success (drone ship)
31,2017-03-30,22:27:00,F9 FT B1021.2,KSC LC-39A,SES-10,5300,GTO,SES,Success,Success (drone ship)
35,2017-06-23,19:10:00,F9 FT B1029.2,KSC LC-39A,BulgariaSat-1,3669,GTO,Bulsatcom,Success,Success (drone ship)
36,2017-06-25,20:25:00,F9 FT B1036.1,VAFB SLC-4E,Iridium NEXT 2,9600,LEO,Iridium Communications,Success,Success (drone ship)
39,2017-08-24,18:51:00,F9 FT B1038.1,VAFB SLC-4E,Formosat-5,475,SSO,NSPO,Success,Success (drone ship)
41,2017-10-09,12:37:00,F9 B4 B1041.1,VAFB SLC-4E,Iridium NEXT 3,9600,Polar LEO,Iridium Communications,Success,Success (drone ship)
42,2017-10-11,22:53:00,F9 FT B1031.2,KSC LC-39A,SES-11 / EchoStar 105,5200,GTO,SES EchoStar,Success,Success (drone ship)
43,2017-10-30,19:34:00,F9 B4 B1042.1,KSC LC-39A,Koreasat 5A,3500,GTO,KT Corporation,Success,Success (drone ship)
52,2018-04-18,22:51:00,F9 B4 B1045.1,CCAFS SLC-40,Transiting Exoplanet Survey Satellite (TESS),362,HEO,NASA (LSP),Success,Success (drone ship)
53,2018-05-11,20:14:00,F9 B5 B1046.1,KSC LC-39A,Bangabandhu-1,3600,GTO,Thales-Alenia/BTRC,Success,Success (drone ship)

### Task 7




##### List the total number of successful and failure mission outcomes

In [32]:
df['Mission_Outcome'].value_counts()

Mission_Outcome
Success                             98
Failure (in flight)                  1
Success (payload status unclear)     1
Success                              1
Name: count, dtype: int64

### Task 8



##### List the   names of the booster_versions which have carried the maximum payload mass. Use a subquery

In [35]:
df[df['PAYLOAD_MASS__KG_'] == df['PAYLOAD_MASS__KG_'].max()]['Booster_Version'].value_counts()

Booster_Version
F9 B5 B1048.4     1
F9 B5 B1049.4     1
F9 B5 B1051.3     1
F9 B5 B1056.4     1
F9 B5 B1048.5     1
F9 B5 B1051.4     1
F9 B5 B1049.5     1
F9 B5 B1060.2     1
F9 B5 B1058.3     1
F9 B5 B1051.6     1
F9 B5 B1060.3     1
F9 B5 B1049.7     1
Name: count, dtype: int64

### Task 9


##### List the records which will display the month names, failure landing_outcomes in drone ship ,booster versions, launch_site for the months in year 2015.

**Note: SQLLite does not support monthnames. So you need to use  substr(Date, 6,2) as month to get the months and substr(Date,0,5)='2015' for year.**

In [36]:
df.head(10)

,Date,Time (UTC),Booster_Version,Launch_Site,Payload,PAYLOAD_MASS__KG_,Orbit,Customer,Mission_Outcome,Landing_Outcome
0,2010-06-04,18:45:00,F9 v1.0 B0003,CCAFS LC-40,Dragon Spacecraft Qualification Unit,0,LEO,SpaceX,Success,Failure (parachute)
1,2010-12-08,15:43:00,F9 v1.0 B0004,CCAFS LC-40,"Dragon demo flight C1, two CubeSats, barrel of...",0,LEO (ISS),NASA (COTS) NRO,Success,Failure (parachute)
2,2012-05-22,7:44:00,F9 v1.0 B0005,CCAFS LC-40,Dragon demo flight C2,525,LEO (ISS),NASA (COTS),Success,No attempt
3,2012-10-08,0:35:00,F9 v1.0 B0006,CCAFS LC-40,SpaceX CRS-1,500,LEO (ISS),NASA (CRS),Success,No attempt
4,2013-03-01,15:10:00,F9 v1.0 B0007,CCAFS LC-40,SpaceX CRS-2,677,LEO (ISS),NASA (CRS),Success,No attempt
5,2013-09-29,16:00:00,F9 v1.1 B1003,VAFB SLC-4E,CASSIOPE,500,Polar LEO,MDA,Success,Uncontrolled (ocean)
6,2013-12-03,22:41:00,F9 v1.1,CCAFS LC-40,SES-8,3170,GTO,SES,Success,No attempt
7,2014-01-06,22:06:00,F9 v1.1,CCAFS LC-40,Thaicom 6,3325,GTO,Thaicom,Success,No attempt
8,2014-04-18,19:25:00,F9 v1.1,CCAFS LC-40,SpaceX CRS-3,2296,LEO (ISS),NASA (CRS),Success,Controlled (ocean)
9,2014-07-14,15:15:00,F9 v1.1,CCAFS LC-40,OG2 Mission 1 6 Orbcomm-OG2 satellites,1316,LEO,Orbcomm,Success,Controlled (ocean)

### Task 10




##### Rank the count of landing outcomes (such as Failure (drone ship) or Success (ground pad)) between the date 2010-06-04 and 2017-03-20, in descending order.

### Reference Links

* <a href ="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Labs_Coursera_V5/labs/Lab%20-%20String%20Patterns%20-%20Sorting%20-%20Grouping/instructional-labs.md.html?origin=www.coursera.org">Hands-on Lab : String Patterns, Sorting and Grouping</a>  

*  <a  href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Labs_Coursera_V5/labs/Lab%20-%20Built-in%20functions%20/Hands-on_Lab__Built-in_Functions.md.html?origin=www.coursera.org">Hands-on Lab: Built-in functions</a>

*  <a  href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Labs_Coursera_V5/labs/Lab%20-%20Sub-queries%20and%20Nested%20SELECTs%20/instructional-labs.md.html?origin=www.coursera.org">Hands-on Lab : Sub-queries and Nested SELECT Statements</a>

*   <a href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Module%205/DB0201EN-Week3-1-3-SQLmagic.ipynb">Hands-on Tutorial: Accessing Databases with SQL magic</a>

*  <a href= "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Module%205/DB0201EN-Week3-1-4-Analyzing.ipynb">Hands-on Lab: Analyzing a real World Data Set</a>

## Author(s)

<h4> Lakshmi Holla </h4>

## Other Contributors

<h4> Rav Ahuja </h4>

## Change log
| Date | Version | Changed by | Change Description |
|------|--------|--------|---------|
| 2021-07-09 | 0.2 |Lakshmi Holla | Changes made in magic sql|
| 2021-05-20 | 0.1 |Lakshmi Holla | Created Initial Version |

## <h3 align="center"> © IBM Corporation 2021. All rights reserved. <h3/>